complexity:
  LongMethod:
    threshold: 400
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
  CyclomaticComplexMethod:
    threshold: 45
  ComplexCondition:
    threshold: 5
  NestedBlockDepth:
    threshold: 7
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10

style:
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  UseCheckOrError:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  UnusedPrivateProperty:
    active: false
  UnusedParameter:
    active: false

naming:
  FunctionNaming:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
  SwallowedException:
    active: false
